version: '2'
services:
    simplesdlc-app:
        image: simplesdlc
        external_links:
            - simplesdlc-mongodb:mongodb
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017
            - SPRING_DATA_MONGODB_DATABASE=simplesdlc
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    simplesdlc-mongodb:
        extends:
            file: mongodb.yml
            service: simplesdlc-mongodb
